# Generated by Django 6.0 on 2025-12-16 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.city')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_aqi', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('prediction_date', models.DateField()),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.city')),
            ],
            options={
                'db_table': 'predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AQIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.IntegerField()),
                ('co', models.FloatField(help_text='Carbon Monoxide (μg/m³)')),
                ('no', models.FloatField(help_text='Nitrogen Monoxide (μg/m³)', null=True)),
                ('no2', models.FloatField(help_text='Nitrogen Dioxide (μg/m³)')),
                ('o3', models.FloatField(help_text='Ozone (μg/m³)')),
                ('so2', models.FloatField(help_text='Sulphur Dioxide (μg/m³)')),
                ('pm25', models.FloatField(help_text='Fine Particles Matter (μg/m³)')),
                ('pm10', models.FloatField(help_text='Coarse Particulate Matter (μg/m³)')),
                ('nh3', models.FloatField(help_text='Ammonia (μg/m³)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.city')),
            ],
            options={
                'db_table': 'aqi_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', '-timestamp'], name='aqi_reading_city_id_96d26f_idx'), models.Index(fields=['aqi'], name='aqi_reading_aqi_f2230d_idx')],
            },
        ),
    ]
